"""Configuration publique integree au tool (sans secrets)."""

GITHUB_REPO = "devdee162-web/qsddddqsddqsdqsd"
CATEGORY_ID = "1520602288635252886"
GUILD_ID = "1517687967085494364"
EXCLUDED_CHANNELS = "1521941017312362526,1521899575101882499"
OUTPUT_DIR = "export_discord"
DOSSIERS_DIR = "dossiers"
DOSSIER_PREFIX = "📂"
ACCOUNTS_FILE = "accounts.json"
WEB_HOST = "0.0.0.0"
WEB_PORT = "8765"
SYNC_VM_ENABLED = "true"
SYNC_VM_HOST = ""
SYNC_VM_USER = "Discord"
SYNC_VM_SHARE = "tool_oap"
AUTO_UPDATE_ON_START = "true"
AUTO_MODE = "true"
AUTO_SYNC_ON_START = "false"
UPDATE_CHECK_HOURS = "24"

PUBLIC_DEFAULTS = {
    "GITHUB_REPO": GITHUB_REPO,
    "CATEGORY_ID": CATEGORY_ID,
    "GUILD_ID": GUILD_ID,
    "EXCLUDED_CHANNELS": EXCLUDED_CHANNELS,
    "OUTPUT_DIR": OUTPUT_DIR,
    "DOSSIERS_DIR": DOSSIERS_DIR,
    "DOSSIER_PREFIX": DOSSIER_PREFIX,
    "ACCOUNTS_FILE": ACCOUNTS_FILE,
    "WEB_HOST": WEB_HOST,
    "WEB_PORT": WEB_PORT,
    "SYNC_VM_ENABLED": SYNC_VM_ENABLED,
    "SYNC_VM_HOST": SYNC_VM_HOST,
    "SYNC_VM_USER": SYNC_VM_USER,
    "SYNC_VM_SHARE": SYNC_VM_SHARE,
    "AUTO_UPDATE_ON_START": AUTO_UPDATE_ON_START,
    "AUTO_MODE": AUTO_MODE,
    "AUTO_SYNC_ON_START": AUTO_SYNC_ON_START,
    "UPDATE_CHECK_HOURS": UPDATE_CHECK_HOURS,
}
